version: '3'

services:
    kanban-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kanban-api
        image: kanban-backend
        ports:
            - '5050:5050'
        depends_on:
        - mongodb

    mongodb:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=kanban-api
            - MONGO_INITDB_ROOT_PASSWORD=DBpassword
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db:
