version: '3'

services:
    kanban-api:
        build:
            context: .
            args:
                NODE_ENV: production
            # target: production
        environment:
            - NODE_ENV=production
        command: yarn start
